### ISSUE TITLE
Can texts be in groups?

### ISSUE THREAD

**Issue by Vayel** [IEMLdev/Intlekt-editor#15]
In the tag editor, when the user creates a USL (a text), should he be able to insert it in groups? What type of groups?

**Comment by ogrergo** [comment]
I think a group must be a hand-picked subset of the library. So I must be able to reference every type of syntactic structures (words, sentences, super-sentences, and texts).
I don't think that a group has a "type", it has only filters (glossary -> filter the terms, lexicon -> filter the words).
