### ISSUE TITLE
Server Error when removing/adding an usl to a keyword

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#173]
Dans le modal des posts de la page "library"... "remove keyword" enlève seulement des tags ou bien les keywords des documents eux-mêmes? Par exemple, je voudrais changer mon topic "critique" et le remplacer par un autre IEML, comment dois-je faire?

**Comment by plevyieml** [comment]
En fait j'ai essayé d'enlever le keyword "critique" dans le modal et la petite roue dentée *tourne sans fin* En fait je n'arrive pas à éditer quoi que ce soit dans ce modal :-()

**Comment by ogrergo** [comment]
Le modal est là pour enlever les keywords des documents, pour retirer l'association (keyword, usl), il faut: 
 - sélectionner ton keyword
 - utiliser la petite croix (en dessous de "Tag:") à coté du nom de l'usl que tu veux retirer
-> tu vas voir un message "Server error 500" mais l'association se fait bien

**Comment by ogrergo** [comment]
Le message serveur Error est provoqué par un plantage de la ré-indexation de la collection

**Comment by plevyieml** [comment]
Merci pour ces réponses!
