### ISSUE TITLE
Problèmes avec l'éditeur de dictionnaire

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#186]
Après avoir créé un paradigme et l'avoir presque rempli, l'éditeur est bloqué. Remarque: le second écran est arrivé avant le premier.

<img width="1181" alt="Screenshot 2019-06-04 14 41 30" src="https://user-images.githubusercontent.com/19435943/58905124-03b82080-86d7-11e9-8b80-7891698032d5.png">
<img width="1301" alt="Screenshot 2019-06-04 14 34 05" src="https://user-images.githubusercontent.com/19435943/58905125-0450b700-86d7-11e9-9fad-601f98b4a7fa.png">

**Comment by ogrergo** [comment]
J'ai reduit la mémoire utilisée par le serveur, ça devrait résoudre la seconde image, pour la première, peut-être que c'était lié au probleme de mémoire, mais pas sûr.

**Comment by ogrergo** [comment]
Tu peux essayer de traduire à nouveau E:M:A:.t.o.-, moi ça à marché. Si ça plante de nouveau, est ce que tu peux me décrire comment tu as fais ?
