### ISSUE TITLE
après avoir marché pendant une heure, l'éditeur de dictionnaire a encore bloqué

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#189]
Peut-être que c'est normal parce que j'ai fait beaucoup de modif et qu'il faut attendre demain 😬
<img width="1386" alt="Screenshot 2019-10-19 14 47 04" src="https://user-images.githubusercontent.com/19435943/67150013-2743c800-f280-11e9-95cb-6d0648e8b152.png">

**Comment by ogrergo** [comment]
Est ce que c'est toujours le cas ? si non, tu peux fermer l'issue
