### ISSUE TITLE
défaut de la recherche sur Intlekt

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#194]
Quand je cherche *la ou *l.a.- sur intlekt, je ne trouve ni **k.e.-l.a.-'** ni **m.e.-l.a.-'** ni **n.e.-l.a.-'** mais seulement ce qui _commence_ par _la_

**Comment by ogrergo** [comment]
C'est réparé, aussi le cas de figure où "esprit" ne matchait pas "l'esprit"
