### ISSUE TITLE
amélioration interface visualisation mots

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#198]
Dans la visualisation colorée des mots, il faudrait autant que possible que les étiquettes s'alignent verticalement. Que le "blanc" des étiquettes de flexion commence toujours sur la même verticale et que le "blanc" des étiquettes de poly-morphème commence toujours sur la même verticale. 
La verticale de début des étiquettes de poly-morphème pourrait être calculée en fonction de la longueur maximale des morphèmes de contenu. Pour faciliter les choses, je peux raccourcir les traduction des morphèmes de flexion...

**Comment by ogrergo** [comment]
![mot_1](https://user-images.githubusercontent.com/3877347/71097250-b89ac200-217d-11ea-8801-7024460553f1.jpg)
C'est comme ça pour le moment

**Comment by ogrergo** [comment]
comme les descendants d'un lexemes sont indentés par rapport au parent, ça décale également les séparations. Je peux faire en sorte que tout le monde soit au même niveau mais dans le cas d'un très grand nombre de descendants (arbre très profond), tous les lexemes seront alignés sur le lexeme le plus indenté, ce qui reduira la place disponible pour tout le monde.

**Comment by ogrergo** [comment]
@plevyieml est ce que tu veux que je change pour tous les aligner ?

**Comment by plevyieml** [comment]
Oui si tu peux 

Envoyé de mon iPhone

**Comment by plevyieml** [comment]
Non c'est bien comme ça, parce que les indentations donnent une information importante.

**Comment by plevyieml** [comment]
OK 👍 donc il vaut mieux rester comme çà 

Envoyé de mon iPhone
