### ISSUE TITLE
Manque les repères temporels dans le menu des flexions actants et qualité

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#199]
Dans le menu des flexions des actants et des qualités, il manque les "repères temporels"
E:.O:O:.O:.-t.o.-'
https://dev.intlekt.io/morpheme/E:.O:O:.O:.-t.o.-'

**Comment by ogrergo** [comment]
Pour les flexions, tu n'as pas mis de repère temporelle pour les qualités dans ton documents :
![pas repere temp pour les qualité](https://user-images.githubusercontent.com/3877347/72159538-8fd7a800-338a-11ea-8c07-0c6ea816f09d.png)

**Comment by plevyieml** [comment]
Désolé, OK, on les ajoute!
