### ISSUE TITLE
Erreur de copie des mots dans le "word" repository

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#201]
Un grand nombre de mots dans le main repository des mots (presque tous ceux que j'ai regardé) ont l'erreur d'être au mode optatif (la flexion E:.-'wu.-S:.-'t.o.-',) au lieu d'être au mode infinitif  (E:.-'we.-S:.-'t.o.-',) contrairement aux exemples donnés dans le manuel.

**Comment by ogrergo** [comment]
Duplicate of #202
