### ISSUE TITLE
ne pas ajouter automatiquement les flexions singulier et indéfini aux mots-actants

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#202]
Plus je relis la liste des mots et des poly-morphèmes contenue dans le "main", plus je vois de problèmes. Il faudrait que je puisse les revoir et corriger tous. 
Par exemple, l'ajout des flexions "singulier" et "indéfini" aux mots-actants ne fait que compliquer la lecture et brouiller les pistes.
Donc  je précise:
Il faut supprimer : 

Dans les process:
- le mode infinitif E:.-'we.-S:.-'t.o.-',
- le mode optatif E:.-'wu.-S:.-'t.o.-',
- La voie active E:.-wa.-t.o.-'

Dans les actants: 
Le singulier E:.wo.-
L'indéfini E:S:.-d.u.-'

**Comment by ogrergo** [comment]
Je suis d'accord, je suis pour les retirer toutes. Je vais faire ça en même temps que l'autre issue "optatif" -> "infinitif".
Dans cette optique, je peux aussi bien retirer les "optatifs" au lieu de les transformer en "infinitif"

**Comment by ogrergo** [comment]
Je suis d'accord, je suis pour les retirer toutes. Je vais faire ça en même temps que

**Comment by ogrergo** [comment]
@plevyieml

**Comment by plevyieml** [comment]
Oui, il faut supprimer les optatifs, les infinitifs, les singuliers et les indéfinis!
