### ISSUE TITLE
Permettre le search par tag

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#204]
Le search par tag n'est pas prioritaire mais ce sera très pratique pour s'y retrouver et surtout pour faire les démos!
Et puis c'est frustrant d'inscrire les tags et de ne pas pouvoir les utiliser ensuite 😬

**Comment by ogrergo** [comment]
Le search par tag fonctionne avec le prefix "#" (comme pour l'ieml avec le prefix "*"), aussi tu peux mettre à jour les tags désormais, ça fonctionne

**Comment by plevyieml** [comment]
Fantastique merci!
