### ISSUE TITLE
élargir la fenêtre d'édition des traductions

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#206]
Élargir la micro-fenêtre pour écrire les traductions des poly-morphèmes, lexèmes, mots, etc.

**Comment by ogrergo** [comment]
De quoi parles tu : 
 - le modal ?
 - la partie propre à chaque langue ?
 - le champ de texte pour entrer les traductions ?

**Comment by plevyieml** [comment]
Le champ de texte pour entrer les traductions
