### ISSUE TITLE
un paradigme de mots apparaît dans les mots et non dans les tables de mots (éditables)

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#207]
J'ai créé un paradigme de mots pour les directions géographiques mais le paradigme apparaît dans ma liste de mots éditables au lieu d'apparaître dans la liste de **tables** de mots éditables

https://dev.intlekt.io/word/[! E:A:.  (E:.-B:.n.-l.-')(m1(l.-S:.U:.-' l.-S:.A:.-') m1(l.-B:.U:.-' l.-B:.A:.-'))]

**Comment by ogrergo** [comment]
Les mots paradigmes apparaissent désormais dans le filtre de table et non plus en sequences singulieres
