### ISSUE TITLE
Le paradigme de l'eau qualifiée...

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#211]
...existe dans la liste (mais dans la liste des mots singuliers et pas celle des tables!)
et elle est marquée comme non créée dans la fenêtre de droite alors qu'elle est créée à gauche. Pourtant, quand on clique sur l'édition, la traduction est bien là!
<img width="1386" alt="Screenshot 2019-12-19 17 26 01" src="https://user-images.githubusercontent.com/19435943/71215249-37c6ed80-2285-11ea-8335-90ef06c7ad5b.png">

**Comment by ogrergo** [comment]
**...existe dans la liste (mais dans la liste des mots singuliers et pas celle des tables!)** => ça c'est corrigé

**et elle est marquée comme non créée dans la fenêtre de droite alors qu'elle est créée à gauche. Pourtant, quand on clique sur l'édition, la traduction est bien là!** => je ne sais pas si ce bug est toujours présent

**Comment by plevyieml** [comment]
"je ne sais pas si ce bug est toujours présent" J'ai essayé hier et il me semble que le bug est toujours là...

**Comment by ogrergo** [comment]
Je pense que j'ai corrigé le problème, mais que ton workspace est coincé dans un état corrompu. Est ce que tu peux:
1. fermer ce workspace
2. le reouvrir via le search avec le boutton dans le menu contextuel "Edit word"
3. me dire si la traduction est présente

Si lors de la traduction d'un prochain mot avec un workspace, la traduction apparaît seulement dans le search mais pas sur le workspace, tu peux reposter un message ici

**Comment by plevyieml** [comment]
"Si lors de la traduction d'un prochain mot avec un workspace, la traduction apparaît seulement dans le search mais pas sur le workspace, tu peux reposter un message ici" D'accord!
