### ISSUE TITLE
Lorsque je clique à gauche sur "potable" ou "non potable" rien n'apparaît dans la fenêtre de droite.

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#216]
Lorsque je clique à gauche sur "potable" ou "non potable" rien n'apparaît dans la fenêtre de droite. Ceci n'arrive que lorsque le type filtré est "lexème".

<img width="1380" alt="potable : non potable" src="https://user-images.githubusercontent.com/19435943/71285098-5800b600-2332-11ea-8617-247344fc1a2b.png">

**Comment by ogrergo** [comment]
C'est normal, la vue des lexèmes n'est pas encore définie, elle dépend de comment le lexème doit s'interpréter, pour le moment il y a deux possibilités:
1) si le lexème ne prend son sens seulement dans un contexte de fct syntagmatique : il faut choisir une fct syntagmatique par défaut (process, actant ou qualité), et la vue du lexème sera la même que le mot avec cette fct syntagmatique. Dans le cas où l'on choisirai la fct syntagmatique actantielle par défaut, le filtre lexeme sera un synonyme de "mot actant avec un seul lexème". Le lexème apparaitera donc également dans le filtre des mots comme un mot simple avec un seul lexème.
2) Sinon le lexème a un sens propre, indépendamment de la fct syntagmatique, qu'il faut alors définir.

**Comment by plevyieml** [comment]
Ceci est une réflexion préliminaire et non une décision. 
A mon sens le problème principal vient de ce que le **lexème = flexion + contenu** et que la flexion dépend de la fonction syntagmatique.
1. si le lexème n'a pas de flexion, il peut s'appliquer à n'importe quelle fonction. Mais un lexème sans flexion = un polymorphème! 
1.1. Devons-nous enregistrer tout polymorphème de contenu automatiquement comme un lexème sans flexion et vice-versa, un peu comme tu proposes de faire apparaître le lexème comme un mot simple ? Dans ce cas, le polymorphème de contenu apparaît dans les polymorphèmes, les lexèmes et les mots! 😲
1.2. Devons-nous interdire d'enregistrer un lexème sans flexion sous prétexte que c'est un polymorphème de contenu et qu'il ne faut pas tout mélanger?
2. Si le lexème a une flexion, celle-ci peut être compatible avec une, deux ou trois fonctions syntagmatiques selon les cas! Il ne peut donc pas être indépendant de la fonction syntagmatique, comme tu le dis dans ton point deux.
3. Une façon de simplifier les choses (et de distinguer les polymorphèmes de contenu et les lexèmes) serait de dire : 
3.1. Un lexème doit avoir une flexion, sinon c'est un polymorphème de contenu
3.2. Un lexème doit avoir aussi un rôle par défaut : process, actant ou qualité, au choix quand on le crée et il apparaît dans le filtre des mots comme un mot simple avec un seul lexème.
3.3. Mais ceci pose un problème (ou au moins demande une convention supplémentaire) car on peut avoir envie d'ajouter une flexion au lexème du genre temps pour un verbe ou pluriel pour un actant.

**Comment by ogrergo** [comment]
Je vois le problème. 
1. lexème sans flexion = un polymorphème : Je suis d'accord, mais ça m'embête un peu que l'écriture d'un **lexème sans flexion** ne soit pas la même qu'un **polymorphème**, il y a les parenthèses en plus.
1.1. Une première idée serait plutôt de faire disparaître le type **lexème** de la base de donnée, et de les stocker seulement en temps que mots simples. Pour le polymorphème, la question se pose aussi: comment interpréter le sens du polymorphème indépendamment du sens du mot ? Pour moi, le polymorphème est plutôt du coté du morphème (le morphème est cas particulier de polymorphème) et le lexème du coté du mot (le lexème est un cas particulier de mot). Dans ce cas, il faut définir comment interpréter le polymorphème (la fct de composition) à partir des morphèmes, sans incidence de ses rôles dans la fct syntagmatique. D'un point de vue de l'écriture, les deux solutions ne conviennent pas car : **lexème sans flexion =/= un polymorphème** et **lexème =/= un mot simple**. Aujourd'hui, l'écriture laisse penser que le lexème est une unité distincte des deux autres niveaux, lorsque l'on aura convergé sur une solution, on aura peut-être à modifier la grammaire pour plus de cohérence.
1.2. Un seconde idée serait de considérer les lexèmes/polymorphèmes/morphèmes comme des paradigmes de mots en faisant varier la fonction syntagmatique (actant/process/qualité). Il faudrait donc inscrire à chaque fois les traductions de ces USLs dans tous ces rôles (une traduction de nom, de verbe et de qualité). Cependant, ça ne résout pas le problèmes des flexions conditionnelles à la fct syntagmatique pour les lexèmes.

2. Alors pour résumer:
2.1. Si **lexème sans flexion == polymorphème** et **lexème != mot simple**, le lexème est un paradigme de fct syntagmatique. On peut changer la grammaire pour que le lexème sans flexion s'écrive de la même manière qu'un polymorphème. On a pas encore résolut le cas des flexions conditionnel de la fct syntagmatique.
2.2. Si **lexème sans flexion != polymorphème** et **lexème == mot simple**, on peut définir une fct syntagmatique par défaut pour tous les lexèmes, et retirer le type de lexème de la base de données. Le filtre "lexème" devient synonyme de "mot simple". Dans ce cas, on peut changer la grammaire pour que le mot simple et le lexème s'écrivent de la même manière.
2.3. Si **lexème sans flexion != polymorphème** et **lexème != mot simple**, il faut définir comment interpréter le lexème. La grammaire n'a pas à être changer. On a toujours le problème des flexions conditionnelles.
2.4. Si **lexème sans flexion == polymorphème** et **lexème == mot simple**, alors les polymorphèmes sont aussi des mots, et comme pour 2.2., il faut donner une fonction syntagmatique par défaut à tous les polymorphèmes, changer l'écriture pour que l'écriture des polymorphèmes et des mots simples sans flexion coïncide.

**Comment by plevyieml** [comment]
Excellents points!

Je crois que c'est une bonne idée de supprimer le lexème non pas comme "unité conceptuellement distincte dans un mot" mais comme unité "réelle" avec niveau de stockage indépendant. Ça va dans le sens du rasoir d'Occam. Et j'ai relu un peu la base de données : c'est vrai que le lexème fait double emploi ou bien avec les mots simples (lexème avec flexion pleine), ou bien avec les polymorphèmes (lexèmes avec flexion vide).

Je crois que, quelle que soit la solution retenue...
1. Le mot simple et le lexème avec flexion pleine doivent s'écrire de la même manière.
2. Le polymorphème de contenu et le lexème avec flexion vide (ou sans flexion) doivent s'écrire de la même manière

Pour le moment la solution qui me plaît le plus sur le plan théorique est ton option 2.4.
En gros, il n'y a plus que des mots entre les morphèmes et les phrases, mais on distingue conceptuellement les mots simples (un seul lexème) et les mots composés (plusieurs lexèmes). Et parmi les mots simples, il y en aura qui n'auront même pas de flexion. Ainsi, on pourra toujours donner une traduction aux lexèmes d'un mot composé, mais en faisant ça – en réalité – on crée des mots simples!

Je comprends que cela voudrait dire que...

1) il faut donner un rôle syntagmatique à tous les polymorphèmes (process, actant ou qualité). C'est pas mal de boulot pour moi mais après avoir regardé la liste des polymorphèmes, je te demanderais de leur donner à tous automatiquement le rôle d'actant et je ne modifierais que ceux qui sont manifestement des process ou des qualités (une minorité d'entre eux).

2) Il faut changer la notation pour que l'écriture des polymorphèmes et des mots simples sans flexion coïncide. Je te laisse choisir la notation et je pense que ça peut être modifié automatiquement quand tu auras décidé.

Le problème avec cette solution c'est que l'on (PL, pour le moment) serait obligé d'écrire explicitement le sens de tous les mots simples distincts qui ne varient que par un morphème de flexion... y compris pluriel, singulier, temps, mode, affirmatif, négatif, etc... On pourrait s'en sortir en imaginant que tous les morphèmes de flexion qui s'ajoutent à un paquet "contenu + flexion" déjà traduit seraient par défaut définis comme ["contenu + flexion" + morphème de flexion 1 + morphème de flexion 2, etc.]

Rien n'est encore coulé dans le béton, j'attends ta réaction...

**Comment by ogrergo** [comment]
On autorise toutes les flexions pour tous les lexèmes.
Le lexème est un paradigme de mots simple qui fait varier le type de la fonction syntagmatique.

**Comment by plevyieml** [comment]
Et en plus on met maintenant le contenu avant la flexion!
