### ISSUE TITLE
Modifier les noms des paradigmes de flexions pour les causes et les mannières

### ISSUE THREAD

**Issue by ogrergo** [IEMLdev/Intlekt-editor#220]

**Comment by plevyieml** [comment]
Ça y est, et j'ai même changé le nom des têtes de rangée et de colonne, c'est plus clair!
https://dictionary.ieml.io/#/dicEdit/IEML/FR/E%253AM%253A.d.%252BM%253AO%253A.-
https://dictionary.ieml.io/#/dicEdit/IEML/FR/E%253A.O%253A.M%253AO%253A.-
