### ISSUE TITLE
Je n'arrive pas à supprimer un lexème que je viens de créer

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#227]
Je n'arrive pas à supprimer un lexème

<img width="1400" alt="Screenshot 2020-03-11 14 54 58" src="https://user-images.githubusercontent.com/19435943/76453053-7f52a680-63a8-11ea-94d8-b398d11e9cd6.png">

**Comment by ogrergo** [comment]
Il faut que tu recharges le cache de chrome, ta version d'intlekt n'est pas la dernière disponible

**Comment by plevyieml** [comment]
Faut-il que je fasse la recharge tous les jours?
