### ISSUE TITLE
Je n'arrive pas à faire apparaître les flexions de manières et en choisir une

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#233]
1) Je n'arrive pas à faire apparaître les flexions de manières et en choisir une
2) je ne sais pas comment faire disparaître les paradigmes de flexion inutiles
<img width="1115" alt="Screenshot 2020-03-13 17 33 23 probleme p ajouter flexion" src="https://user-images.githubusercontent.com/19435943/76661162-0fcbeb00-6551-11ea-8842-11955ce497ba.png">

**Comment by ogrergo** [comment]
est-ce toujours un problème ?

**Comment by plevyieml** [comment]
Oui c'est toujours un problème. Tout semble bien fonctionner au début, mais qu'on interagit un peu ça commence à mal aller...
Tu vois sur la copie d'écran que le choix dans le menu est "cause" mais que c'est bloqué à "manières"
<img width="528" alt="Screenshot 2020-03-23 14 31 59 les flexions marchent pas" src="https://user-images.githubusercontent.com/19435943/77350652-376e4080-6d13-11ea-888c-2c63ca5ddd18.png">

**Comment by plevyieml** [comment]
Bon, je ne sais pas trop comment, mais j'ai finalement **réussi** à faire fonctionner les flexions! Sur la copie d'écran, tu vois que j'ai réussi à créer le lexème "flocon de neige"!
<img width="1111" alt="Screenshot 2020-03-23 14 42 41 flocon de neige" src="https://user-images.githubusercontent.com/19435943/77351984-de9fa780-6d14-11ea-9ff1-28e4d6b9ce33.png">
