### ISSUE TITLE
Comment éditer?

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#234]
J'ai l'impression qu'il y a deux manières d'éditer un USL à partir du clic droit.
"Display or set translations/tags etc." ET "edit lexeme". Lequel est le bon?
J'ai aussi remarqué que lorsque j'utilise "display" et que je mets un tag, il ne s'enregistre pas. 
<img width="456" alt="Screenshot 2020-03-13 18 12 48 comment éditer" src="https://user-images.githubusercontent.com/19435943/76663095-5a039b00-6556-11ea-9d86-9347bf40d975.png">

**Comment by ogrergo** [comment]
Oui effectivement, il faut que je retire cette fonctionnalité
