### ISSUE TITLE
Permettre l'ordre alphabétique ordinaire dans les listes internes aux tags

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#235]
Pour l'instant l'ordre semble être l'ordre IEML, en particulier, il y a un ordre 
1) poly-morphèmes 
2) lexème, 
3) mots
et à l'intérieur de chaque catégorie les paradigmes viennent avant les singuliers
Je veux l'ordre alphabétique ordinaire pour pouvoir tester des ordres logiques qui vont éclairer la structure des lexiques et permettre de faire de belles démos...

**Comment by ogrergo** [comment]
Il faut que tu me confirmes que l'ordre est correct.

**Comment by plevyieml** [comment]
Pour le moment, dans un tag, j'ai mes USLs classées d'abord par types d'unités (poly-morphèmes, lexèmes, mots) et à l'intérieur de chaque type d'unité c'est rangé par ordre alphabétique ordinaire. L'ordre alphabétique est bien mais... Ce que je voudrais, c'est inverser l'ordre des types d'unités. Donc: mettre d'abord les mots, puis les lexèmes, puis les poly-morphèmes. Au passage il est toujours impossible d'inscrire les morphèmes dans des tags, je vais rajouter l'issue...

**Comment by ogrergo** [comment]
d'accord je n'avais pas compris !

**Comment by plevyieml** [comment]
Toujours au sujet de l'ordre... Bon voilà ce que j'obtiens dans un search sur le contenu d'un tag. Je suppose que "a paradigme des neiges" est à la fin malgré le "a" initial parce que c'est un paradigme... Dans ce cas, est-il possible de mettre toujours les paradigmes au début au lieu de les mettre à la fin?
<img width="1119" alt="Screenshot 2020-03-23 15 39 45 ordre alphabétique" src="https://user-images.githubusercontent.com/19435943/77356532-dd727880-6d1c-11ea-9665-7cfec58ad039.png">
