### ISSUE TITLE
Impossible d'enlever un morphème dans un mot

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#248]
Ici, je ne peux pas enlever *fikitu du lexème principal
<img width="1114" alt="Screenshot 2020-03-24 14 58 06 enlever un morphème" src="https://user-images.githubusercontent.com/19435943/77466096-217a8180-6de0-11ea-9551-e97be83b986a.png">

**Comment by ogrergo** [comment]
faire en sorte que l'on puisse enlever les morphèmes depuis l'arbre

**Comment by ogrergo** [comment]
Duplicate of #261
