### ISSUE TITLE
La seule jonction disponible est un "et"

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#251]
Je ne vois pas comment faire pour créer une autre jonction que "et"
<img width="1112" alt="Screenshot 2020-03-24 15 24 57 Pas autre chose que des  et" src="https://user-images.githubusercontent.com/19435943/77468431-e67a4d00-6de3-11ea-80a7-93bb28c60240.png">

**Comment by ogrergo** [comment]
Ajouter le menu déroulant pour sélectionner la jonction, sur le bouton "créer une jonction"
