### ISSUE TITLE
La visualisation des tables est défectueuse

### ISSUE THREAD

**Issue by plevyieml** [IEMLdev/Intlekt-editor#254]
Lorsque l'on affiche un paradigme racine qui comprend plusieurs tables, Intlekt affiche seulement la première table et faut faire une recherche malaisée dans les relations pour trouver les autres tables.
Dans l'exemple ci-dessous on a l'impression que les seules mers sont aux pôles.
<img width="1073" alt="Screenshot 2020-03-29 12 49 48 Océan autre table" src="https://user-images.githubusercontent.com/19435943/77855100-5b6ecd80-71bc-11ea-8f65-dd902c7a4724.png">

**Comment by ogrergo** [comment]
autrement tu as les boutons juste au dessus des tables qui te permettent de changer de table[
![77855100-5b6ecd80-71bc-11ea-8f65-dd902c7a4724](https://user-images.githubusercontent.com/3877347/78180494-d6d8b500-7430-11ea-9973-da5564eddc82.jpg)
](url)

**Comment by ogrergo** [comment]
je vais améliorer cette interface

**Comment by ogrergo** [comment]
Afficher les tables les unes en dessous des autres dans le cas d'un paradigme racine additif
