### ISSUE TITLE
Order usl by alphabetical order on the fr/en in the library navigation

### ISSUE THREAD

**Issue by ogrergo** [IEMLdev/Intlekt-editor#33]

**Comment by ogrergo** [comment]
- for the moment, order everything with alphabetical order
- after order the word-term by ieml order (index field of term object)

**Comment by Vayel** [comment]
ec94d89

**Comment by Vayel** [comment]
After having added the `index` field to the model `TermWord`, use `meta.ordering` on the model or, if it does not work, a custom queryset: http://docs.mongoengine.org/guide/querying.html#custom-querysets.
