### ISSUE TITLE
Add error fields on every form

### ISSUE THREAD

**Issue by PiggyGenius** [IEMLdev/Intlekt-editor#49]

**Comment by Vayel** [comment]
* https://github.com/IEMLdev/Intlekt-editor/blob/master/src/scripts/lib/lib.js#L27
* https://github.com/IEMLdev/Intlekt-editor/blob/master/src/scripts/components/usl-creator.js#L304

**Comment by PiggyGenius** [comment]
First solve the related issues on the scraper side.

**Comment by PiggyGenius** [comment]
There needs to be websockets for clean implementation
